/** All US states, DC, and populated territories. Used to render the picker with "coming soon" placeholders. */
export const ALL_JURISDICTIONS: { code: string; en: string; es: string }[] = [
  { code: 'AL', en: 'Alabama', es: 'Alabama' }, { code: 'AK', en: 'Alaska', es: 'Alaska' }, { code: 'AZ', en: 'Arizona', es: 'Arizona' },
  { code: 'AR', en: 'Arkansas', es: 'Arkansas' }, { code: 'CA', en: 'California', es: 'California' }, { code: 'CO', en: 'Colorado', es: 'Colorado' },
  { code: 'CT', en: 'Connecticut', es: 'Connecticut' }, { code: 'DE', en: 'Delaware', es: 'Delaware' }, { code: 'DC', en: 'District of Columbia', es: 'Distrito de Columbia' },
  { code: 'FL', en: 'Florida', es: 'Florida' }, { code: 'GA', en: 'Georgia', es: 'Georgia' }, { code: 'HI', en: 'Hawaii', es: 'Hawái' },
  { code: 'ID', en: 'Idaho', es: 'Idaho' }, { code: 'IL', en: 'Illinois', es: 'Illinois' }, { code: 'IN', en: 'Indiana', es: 'Indiana' },
  { code: 'IA', en: 'Iowa', es: 'Iowa' }, { code: 'KS', en: 'Kansas', es: 'Kansas' }, { code: 'KY', en: 'Kentucky', es: 'Kentucky' },
  { code: 'LA', en: 'Louisiana', es: 'Luisiana' }, { code: 'ME', en: 'Maine', es: 'Maine' }, { code: 'MD', en: 'Maryland', es: 'Maryland' },
  { code: 'MA', en: 'Massachusetts', es: 'Massachusetts' }, { code: 'MI', en: 'Michigan', es: 'Míchigan' }, { code: 'MN', en: 'Minnesota', es: 'Minnesota' },
  { code: 'MS', en: 'Mississippi', es: 'Misisipi' }, { code: 'MO', en: 'Missouri', es: 'Misuri' }, { code: 'MT', en: 'Montana', es: 'Montana' },
  { code: 'NE', en: 'Nebraska', es: 'Nebraska' }, { code: 'NV', en: 'Nevada', es: 'Nevada' }, { code: 'NH', en: 'New Hampshire', es: 'Nuevo Hampshire' },
  { code: 'NJ', en: 'New Jersey', es: 'Nueva Jersey' }, { code: 'NM', en: 'New Mexico', es: 'Nuevo México' }, { code: 'NY', en: 'New York', es: 'Nueva York' },
  { code: 'NC', en: 'North Carolina', es: 'Carolina del Norte' }, { code: 'ND', en: 'North Dakota', es: 'Dakota del Norte' }, { code: 'OH', en: 'Ohio', es: 'Ohio' },
  { code: 'OK', en: 'Oklahoma', es: 'Oklahoma' }, { code: 'OR', en: 'Oregon', es: 'Oregón' }, { code: 'PA', en: 'Pennsylvania', es: 'Pensilvania' },
  { code: 'RI', en: 'Rhode Island', es: 'Rhode Island' }, { code: 'SC', en: 'South Carolina', es: 'Carolina del Sur' }, { code: 'SD', en: 'South Dakota', es: 'Dakota del Sur' },
  { code: 'TN', en: 'Tennessee', es: 'Tennessee' }, { code: 'TX', en: 'Texas', es: 'Texas' }, { code: 'UT', en: 'Utah', es: 'Utah' },
  { code: 'VT', en: 'Vermont', es: 'Vermont' }, { code: 'VA', en: 'Virginia', es: 'Virginia' }, { code: 'WA', en: 'Washington', es: 'Washington' },
  { code: 'WV', en: 'West Virginia', es: 'Virginia Occidental' }, { code: 'WI', en: 'Wisconsin', es: 'Wisconsin' }, { code: 'WY', en: 'Wyoming', es: 'Wyoming' },
  { code: 'PR', en: 'Puerto Rico', es: 'Puerto Rico' }, { code: 'GU', en: 'Guam', es: 'Guam' }, { code: 'VI', en: 'U.S. Virgin Islands', es: 'Islas Vírgenes de EE. UU.' },
  { code: 'AS', en: 'American Samoa', es: 'Samoa Americana' }, { code: 'MP', en: 'Northern Mariana Islands', es: 'Islas Marianas del Norte' },
];
