/* AUTO-GENERATED by pipeline/src/gen-types.ts from schema/*.json. Do not edit. */

/**
 * Ids from this document's `sources` array.
 *
 * @minItems 1
 */
export type SourceRefs = [string, ...string[]];

/**
 * One guide = one jurisdiction x one document/process (name change, driver's license, birth certificate, passport, Social Security, USCIS, TSA/Global Entry). Sections that don't apply to a guide type are simply omitted.
 */
export interface DocumentGuide {
  guide_type:
    | "name_change"
    | "drivers_license"
    | "birth_certificate"
    | "passport"
    | "social_security"
    | "uscis"
    | "tsa_global_entry";
  /**
   * Two-letter state/territory code, or 'US' for federal.
   */
  jurisdiction: string;
  review: Review;
  /**
   * available: the change can be made today. restricted: possible only under narrow conditions (e.g. surgery proof, court order). prohibited: not possible. litigation: availability is actively changing due to a court case; read the banner. unclear: policy is unwritten or inconsistently applied.
   */
  status: "available" | "restricted" | "prohibited" | "litigation" | "unclear";
  status_summary: LocalizedText;
  /**
   * available: the change can be made today. restricted: possible only under narrow conditions (e.g. surgery proof, court order). prohibited: not possible. litigation: availability is actively changing due to a court case; read the banner. unclear: policy is unwritten or inconsistently applied.
   */
  name_change_status?: "available" | "restricted" | "prohibited" | "litigation" | "unclear";
  summary: LocalizedText1;
  /**
   * What the agency requires to change a sex/gender marker.
   */
  requirement_type?:
    | "self_attestation"
    | "provider_letter_any"
    | "provider_letter_limited"
    | "court_order"
    | "amended_birth_certificate"
    | "surgery_proof"
    | "prohibited"
    | "unclear";
  markers_available?: ("M" | "F" | "X")[];
  eligibility?: {
    residency?: LocalizedText2;
    age?: LocalizedText2;
    criminal_history?: LocalizedText2;
    other?: LocalizedText2;
    sources: SourceRefs;
  };
  forms?: Form[];
  /**
   * @minItems 1
   */
  steps: [Step, ...Step[]];
  fees?: Fee[];
  fee_waiver?: {
    available: boolean;
    /**
     * Form ids.
     */
    forms?: string[];
    eligibility?: LocalizedText2;
    how?: LocalizedText2;
    sources: SourceRefs;
  };
  /**
   * Name change only.
   */
  publication?: {
    required: "yes" | "no" | "conditional";
    detail?: LocalizedText2;
    waiver_available?: boolean;
    waiver_how?: LocalizedText2;
    sources: SourceRefs;
  };
  hearing?: {
    required: "yes" | "no" | "conditional";
    detail?: LocalizedText2;
    sources: SourceRefs;
  };
  background_check?: {
    required: "yes" | "no" | "conditional";
    detail?: LocalizedText2;
    sources: SourceRefs;
  };
  /**
   * Record sealing and privacy protections.
   */
  confidentiality?: {
    sealing_available: boolean;
    detail?: LocalizedText2;
    how?: LocalizedText2;
    sources: SourceRefs;
  };
  minors?: {
    summary: LocalizedText2;
    forms?: string[];
    sources: SourceRefs;
  };
  /**
   * How the request can be submitted.
   */
  delivery?: {
    online?: boolean;
    by_mail?: boolean;
    in_person?: boolean;
    detail?: LocalizedText2;
    sources: SourceRefs;
  };
  timeline?: LocalizedText2;
  after?: LocalizedText5;
  tips?: LocalizedText2[];
  local_help?: Resource[];
  statutes?: Citation[];
  litigation?: Litigation[];
  pending_bills?: PendingBill[];
  /**
   * Trusted external guides to point people to (A4TE, Namesake, ACLU affiliate...).
   */
  related_links?: {
    title: string;
    url: string;
    note?: LocalizedText2;
  }[];
  /**
   * @minItems 1
   */
  sources: [Source, ...Source[]];
}
/**
 * Editorial state. The site shows `last_verified` and a badge derived from `status`.
 */
export interface Review {
  /**
   * draft = AI-drafted or unreviewed; reviewed = a human checked every claim against its source.
   */
  status: "draft" | "reviewed";
  /**
   * YYYY-MM-DD
   */
  last_verified: string;
  /**
   * GitHub handle or 'ai-draft'.
   */
  verified_by: string;
  confidence: "low" | "medium" | "high";
  es_status?: "missing" | "machine_draft" | "reviewed";
  /**
   * Internal reviewer notes, not rendered.
   */
  notes?: string;
}
/**
 * One or two sentences for the banner: what is and isn't possible right now.
 */
export interface LocalizedText {
  en: string;
  es?: string;
}
/**
 * Short overview paragraph. Markdown allowed.
 */
export interface LocalizedText1 {
  en: string;
  es?: string;
}
/**
 * Prose in English with optional Spanish. Spanish review state is tracked at the document level in `review.es_status`.
 */
export interface LocalizedText2 {
  en: string;
  es?: string;
}
export interface Form {
  /**
   * Agency form number, e.g. NC-100, DL 329, VS 24.
   */
  id: string;
  name: LocalizedText2;
  url: string;
  /**
   * Official Spanish version if the agency publishes one.
   */
  url_es?: string;
  required: "always" | "conditional" | "optional";
  condition?: LocalizedText2;
  how_to_fill?: LocalizedText3;
  sources: SourceRefs;
}
/**
 * Prose in English with optional Spanish. Spanish review state is tracked at the document level in `review.es_status`.
 */
export interface LocalizedText3 {
  en: string;
  es?: string;
}
export interface Step {
  id: string;
  title: LocalizedText2;
  body: LocalizedText4;
  /**
   * Form ids from this document's `forms`.
   */
  forms?: string[];
  /**
   * Fee ids from this document's `fees`.
   */
  fees?: string[];
  /**
   * Used by the checklist builder to filter steps. Omit for steps that always apply.
   */
  applies_to?: ("adult" | "minor" | "name_change" | "gender_marker" | "in_person" | "by_mail" | "online")[];
  optional?: boolean;
  estimated_time?: LocalizedText2;
  sources: SourceRefs;
}
/**
 * Prose in English with optional Spanish. Spanish review state is tracked at the document level in `review.es_status`.
 */
export interface LocalizedText4 {
  en: string;
  es?: string;
}
export interface Fee {
  id: string;
  label: LocalizedText2;
  /**
   * Use when the fee is a single statewide number.
   */
  amount?: number;
  min?: number;
  max?: number;
  varies_by?: "county" | "court" | "office" | "vendor";
  waivable?: boolean;
  note?: LocalizedText2;
  sources: SourceRefs;
}
/**
 * Prose in English with optional Spanish. Spanish review state is tracked at the document level in `review.es_status`.
 */
export interface LocalizedText5 {
  en: string;
  es?: string;
}
/**
 * A place, org, program, or fund a person can contact. Inline in state/local files; national ones live in content/orgs and are referenced by `org`.
 */
export interface Resource {
  id: string;
  /**
   * Id of an entry in content/orgs, when this resource is a national org's local presence.
   */
  org?: string;
  name: string;
  type:
    | "legal_aid"
    | "name_change_clinic"
    | "lgbtq_center"
    | "fund"
    | "hrt_clinic"
    | "informed_consent_clinic"
    | "telehealth_hrt"
    | "primary_care"
    | "sexual_health"
    | "mental_health"
    | "hotline"
    | "insurance_help"
    | "government_office"
    | "advocacy_org"
    | "other";
  /**
   * @minItems 1
   */
  pillars: [
    "name_change" | "gender_marker" | "hrt" | "sexual_health" | "mental_health" | "insurance",
    ...("name_change" | "gender_marker" | "hrt" | "sexual_health" | "mental_health" | "insurance")[]
  ];
  description: LocalizedText2;
  url?: string;
  phone?: string;
  /**
   * Public business address only. Never a private residence.
   */
  address?: string;
  areas_served?: LocalizedText2;
  cost?: "free" | "sliding_scale" | "low_cost" | "insurance" | "paid" | "varies" | "unknown";
  accepts_medicaid?: boolean;
  accepts_uninsured?: boolean;
  telehealth?: boolean;
  languages?: string[];
  verification: "official_source" | "org_website" | "community_reported" | "unverified";
  sources: SourceRefs;
}
export interface Citation {
  /**
   * e.g. Cal. Code Civ. Proc. § 1277
   */
  cite: string;
  title?: LocalizedText2;
  url: string;
}
export interface Litigation {
  case: string;
  court?: string;
  summary: LocalizedText2;
  effect_today: LocalizedText6;
  /**
   * YYYY-MM-DD
   */
  last_update: string;
  url?: string;
  sources: SourceRefs;
}
/**
 * Prose in English with optional Spanish. Spanish review state is tracked at the document level in `review.es_status`.
 */
export interface LocalizedText6 {
  en: string;
  es?: string;
}
export interface PendingBill {
  /**
   * e.g. HB 1234 (2026)
   */
  bill: string;
  summary: LocalizedText2;
  status: "introduced" | "in_committee" | "passed_one_chamber" | "passed" | "signed" | "vetoed" | "enjoined" | "dead";
  /**
   * YYYY-MM-DD
   */
  last_action: string;
  url?: string;
  sources: SourceRefs;
}
/**
 * A citation. Every rendered claim must trace to one of these via its `id`.
 */
export interface Source {
  id: string;
  url: string;
  title: string;
  publisher?: string;
  kind: "official" | "statute" | "regulation" | "court" | "form" | "org" | "news" | "community";
  /**
   * YYYY-MM-DD
   */
  accessed: string;
  /**
   * Short excerpt supporting the claim, for reviewers and change detection.
   */
  quote?: string;
  /**
   * Include in the monitoring registry.
   */
  watch?: boolean;
}

export interface StateMetadata {
  code: string;
  name: LocalizedText;
  kind: "state" | "district" | "territory";
  review: Review;
  overview: LocalizedText1;
  /**
   * Coarse, sourced signal so people in hostile states are warned early. Keep neutral wording.
   */
  climate: {
    id_documents: "protective" | "mixed" | "restrictive";
    care: "protective" | "mixed" | "restrictive";
    /**
     * State has a law protecting providers/patients of gender-affirming care from out-of-state prosecution.
     */
    shield_law?: boolean;
    sources: SourceRefs;
  };
  /**
   * Which guide files exist for this state; the site uses this to build navigation.
   */
  guides: ("name_change" | "drivers_license" | "birth_certificate" | "care")[];
  /**
   * Slugs of files in local/.
   */
  cities?: string[];
  /**
   * Statewide orgs to show on the state landing page.
   */
  key_resources?: Resource[];
  /**
   * @minItems 1
   */
  sources: [Source, ...Source[]];
}

export interface StateGenderAffirmingCareOverview {
  jurisdiction: string;
  review: Review;
  status_summary: LocalizedText;
  adult_care: {
    /**
     * available: the change can be made today. restricted: possible only under narrow conditions (e.g. surgery proof, court order). prohibited: not possible. litigation: availability is actively changing due to a court case; read the banner. unclear: policy is unwritten or inconsistently applied.
     */
    status: "available" | "restricted" | "prohibited" | "litigation" | "unclear";
    detail: LocalizedText;
    sources: SourceRefs;
  };
  minor_care: {
    /**
     * available: the change can be made today. restricted: possible only under narrow conditions (e.g. surgery proof, court order). prohibited: not possible. litigation: availability is actively changing due to a court case; read the banner. unclear: policy is unwritten or inconsistently applied.
     */
    status: "available" | "restricted" | "prohibited" | "litigation" | "unclear";
    detail: LocalizedText;
    sources: SourceRefs;
  };
  medicaid: {
    /**
     * e.g. Medi-Cal
     */
    program_name?: string;
    covers_hrt: "yes" | "no" | "partial" | "unclear";
    covers_surgery: "yes" | "no" | "partial" | "unclear";
    detail: LocalizedText;
    how_to_apply_url?: string;
    sources: SourceRefs;
  };
  private_insurance?: {
    nondiscrimination_protection: boolean;
    detail: LocalizedText;
    complaint_url?: string;
    sources: SourceRefs;
  };
  /**
   * Ids of telehealth orgs (content/orgs) that serve this state.
   */
  telehealth_hrt?: string[];
  /**
   * Statewide care resources (clinics with many sites, funds, insurance navigators).
   */
  resources?: Resource[];
  statutes?: Citation[];
  litigation?: Litigation[];
  pending_bills?: PendingBill[];
  /**
   * @minItems 1
   */
  sources: [Source, ...Source[]];
}

export interface CityMetroResources {
  jurisdiction: string;
  slug: string;
  /**
   * e.g. Los Angeles
   */
  name: string;
  area?: LocalizedText;
  review: Review;
  intro: LocalizedText1;
  /**
   * Where name change petitions are filed locally.
   */
  court?: {
    name: string;
    url?: string;
    self_help_url?: string;
    filing_fee?: number;
    notes?: LocalizedText1;
    sources: SourceRefs;
  };
  /**
   * @minItems 1
   */
  resources: [Resource, ...Resource[]];
  /**
   * @minItems 1
   */
  sources: [Source, ...Source[]];
}

export interface NationalOrMultiStateOrganization {
  id: string;
  name: string;
  url: string;
  type:
    | "legal_aid"
    | "name_change_clinic"
    | "lgbtq_center"
    | "fund"
    | "hrt_clinic"
    | "informed_consent_clinic"
    | "telehealth_hrt"
    | "primary_care"
    | "sexual_health"
    | "mental_health"
    | "hotline"
    | "insurance_help"
    | "government_office"
    | "advocacy_org"
    | "other";
  /**
   * @minItems 1
   */
  pillars: [
    "name_change" | "gender_marker" | "hrt" | "sexual_health" | "mental_health" | "insurance",
    ...("name_change" | "gender_marker" | "hrt" | "sexual_health" | "mental_health" | "insurance")[]
  ];
  review: Review;
  description: LocalizedText;
  scope: "national" | "multi_state" | "regional";
  /**
   * Two-letter codes, or ['ALL'].
   */
  states_served: string[];
  states_excluded?: string[];
  cost: "free" | "sliding_scale" | "low_cost" | "insurance" | "paid" | "varies" | "unknown";
  cost_detail?: LocalizedText;
  accepts_insurance?: boolean;
  accepts_medicaid?: boolean;
  serves_minors?: boolean;
  telehealth?: boolean;
  phone?: string;
  languages?: string[];
  /**
   * For funds/grants especially.
   */
  program_status?: "active" | "paused" | "waitlist" | "closed" | "unknown";
  notes?: LocalizedText;
  /**
   * @minItems 1
   */
  sources: [Source, ...Source[]];
}

export interface Glossary {
  terms: {
    id: string;
    term: LocalizedText;
    definition: LocalizedText;
  }[];
}

/**
 * Every URL the monitor watches. Mostly generated from `sources[]` across content; hand-added entries cover feeds and APIs.
 */
export interface MonitoringSourceRegistry {
  sources: {
    id: string;
    url: string;
    kind: "html" | "pdf" | "json_api" | "rss" | "docket";
    /**
     * browser = headless Playwright for sites that block plain HTTP clients.
     */
    fetch?: "plain" | "browser";
    frequency?: "daily" | "weekly" | "monthly";
    /**
     * Optional CSS selector to scope the watched region.
     */
    selector?: string;
    /**
     * Repo-relative content paths that cite this source.
     */
    linked_content: string[];
    jurisdiction?: string;
    severity_hint?: "critical" | "normal" | "low";
  }[];
}

