/**
 * Builds sources/registry.yaml: one entry per unique URL cited anywhere in content/, plus the hand-maintained
 * entries in sources/manual.yaml. Run after content changes: npm run registry -w pipeline
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import YAML from 'yaml';
import { loadContent } from './load.js';
import { ROOT } from './paths.js';

type Entry = {
  id: string; url: string; title?: string; kind: 'html' | 'pdf' | 'json_api' | 'rss' | 'docket';
  fetch: 'auto' | 'plain' | 'browser' | 'manual'; frequency: 'daily' | 'weekly' | 'monthly';
  linked_content: string[]; jurisdiction?: string; severity_hint?: 'critical' | 'normal' | 'low'; note?: string;
};

const manual = YAML.parse(fs.readFileSync(path.join(ROOT, 'sources/manual.yaml'), 'utf8')) as {
  manual_domains: { domain: string; note: string }[]; browser_domains: string[]; extra: Partial<Entry>[];
};
const hostMatches = (url: string, domain: string) => {
  const h = new URL(url).hostname.replace(/^www\./, '');
  return h === domain || h.endsWith('.' + domain);
};

const byUrl = new Map<string, Entry>();
const idFor = (url: string) => 'u' + crypto.createHash('sha1').update(url).digest('hex').slice(0, 10);

for (const f of loadContent()) {
  if (!f.rel.startsWith('content/') || !f.data) continue;
  const doc = f.data as { sources?: { url: string; title: string; kind: string; watch?: boolean }[]; jurisdiction?: string; code?: string };
  const jurisdiction = doc.jurisdiction ?? doc.code ?? (f.rel.startsWith('content/states/') ? f.rel.split('/')[2] : 'US');
  const isOrg = f.rel.startsWith('content/orgs/');
  for (const s of doc.sources ?? []) {
    if (s.watch === false) continue;
    const e = byUrl.get(s.url) ?? {
      id: idFor(s.url), url: s.url, title: s.title,
      kind: /\.pdf($|\?)/i.test(s.url) ? 'pdf' : 'html',
      fetch: 'auto', frequency: 'weekly', linked_content: [], jurisdiction: isOrg ? undefined : jurisdiction,
      // Government and legal sources drive statuses; org pages drive resource listings.
      severity_hint: ['official', 'statute', 'regulation', 'court', 'form'].includes(s.kind) ? 'normal' : 'low',
    } as Entry;
    if (!e.linked_content.includes(f.rel)) e.linked_content.push(f.rel);
    if (jurisdiction === 'US' && !isOrg) e.frequency = 'daily'; // federal policy moves fast
    byUrl.set(s.url, e);
  }
}

for (const x of manual.extra) byUrl.set(x.url!, { fetch: 'auto', frequency: 'weekly', linked_content: [], ...x } as Entry);

for (const e of byUrl.values()) {
  let host: string;
  try { host = new URL(e.url).hostname; } catch { continue; }
  const m = manual.manual_domains.find((d) => hostMatches(e.url, d.domain));
  if (m) { e.fetch = 'manual'; e.note = m.note; }
  else if (manual.browser_domains.some((d) => hostMatches(e.url, d))) e.fetch = 'browser';
  if (!host) continue;
}

const sources = [...byUrl.values()].sort((a, b) => (a.jurisdiction ?? 'ZZ').localeCompare(b.jurisdiction ?? 'ZZ') || a.url.localeCompare(b.url));
const out = { sources: sources.map((e) => Object.fromEntries(Object.entries(e).filter(([, v]) => v !== undefined))) };
fs.writeFileSync(path.join(ROOT, 'sources/registry.yaml'),
  '# AUTO-GENERATED by pipeline/src/build-registry.ts. Edit sources/manual.yaml instead.\n' + YAML.stringify(out, { lineWidth: 0 }));
const count = (k: string) => sources.filter((s) => s.fetch === k).length;
console.log(`✔ ${sources.length} sources (auto ${count('auto')}, browser ${count('browser')}, manual ${count('manual')})`);
