/** Generates site/src/types/content.d.ts from schema/*.json so Astro components get typed content. */
import fs from 'node:fs';
import path from 'node:path';
import { compile } from 'json-schema-to-typescript';
import { SCHEMA_DIR, SITE_TYPES_OUT } from './paths.js';

const files = ['guide.json', 'state-meta.json', 'care.json', 'local.json', 'org.json', 'glossary.json', 'source-registry.json'];
let out = `/* AUTO-GENERATED by pipeline/src/gen-types.ts from schema/*.json. Do not edit. */\n\n`;
for (const f of files) {
  const schema = JSON.parse(fs.readFileSync(path.join(SCHEMA_DIR, f), 'utf8'));
  const ts = await compile(schema, path.basename(f, '.json'), {
    cwd: SCHEMA_DIR,
    bannerComment: '',
    declareExternallyReferenced: f === 'guide.json', // emit shared $defs once
    additionalProperties: false,
  });
  out += ts + '\n';
}
fs.mkdirSync(path.dirname(SITE_TYPES_OUT), { recursive: true });
fs.writeFileSync(SITE_TYPES_OUT, out);
console.log(`✔ wrote ${path.relative(process.cwd(), SITE_TYPES_OUT)}`);
